export function getMappedTitle(title: string, mappings: Record<string, string>) {
  const mappedTitle = mappings[title];

  if (mappedTitle) {
    return mappedTitle;
  }

  return title;
}

export const examTitlesMapping = {
  "rn - intensive care unit (icu) nurse": "rn - intensive care unit (icu)",
  "rn - stepdown_ intermediate care_ progressive care unit": "rn - stepdown/intermediate care/progressive care (pcu)",
  "rn - psychiatric – adult": "rn - psychiatric - adult",
  "rn - intensive care unit (picu) - pediatric": "rn - intensive care unit - pediatrics (picu)",
  "rn - intensive care unit medication - pediatric": "rn - pediatric medication",
  "rn - pediatric": "rn - pediatrics",
  "rn - operating room (or)/ perioperative - adult": "rn - operating room (or) / perioperative - adult",
  "rn - mother baby and nursery": "rn - mother-baby and nursery",
  "rn – stepdown / intermediate care / progressive care unit exam":
    "rn - stepdown/intermediate care/progressive care (pcu)",
  "rn/lpn/lvn - dementia care": "rn - dementia care, lpn / lvn - dementia care",
  "cardiac rhythm strip identification": "basic ekg with lethal rhythms",
  "rn - covid-19 screening/immunization": "rn - covid-19 screening / immunization",
  "clinical nurse manager": "rn - clinical manager",
  "ishihara compliant color vision exam": "ishihara compliant color vision exam (17 plates)",
  "core mandatory exam (allied/non-nursing)": "core mandatory exam - allied/non-nursing",
  "lpn/lvn - adult/general": "lpn / lvn - adult / general",
  "cna – adult/general": "cna - adult/general",
  "lpn/lvn - school": "lpn / lvn - school",
  "sterile processing technician (spt)": "sterile processing technician",
  "psychiatric technician medication exam": "psychiatric technician medication",
  "obstetric ultrasound": "sonographer - obstetrics",
  "rn - long term care": "rn - long-term care",
  "family nurse practitioner": "nurse practitioner - adult",
  "lpn/lvn - long term care": "lpn / lvn - long term care",
  "electrocardiogram (ekg) technician": "electrocardiogram (ekg/ecg) technician",
  "mental health aide": "mental health aide (mha) - adult",
  "clinical microbiologist /clinical lab specialist": "clinical microbiologist - clinical laboratory specialist",
  "rn-clinic/ambulatory": "rn - ambulatory / clinic",
  "lpn/lvn - correctional": "lpn / lvn - correctional",
  "licensed clinical social worker (lcsw)": "licensed clinical social worker",
  "lpn/lvn - acute care": "lpn / lvn - acute care",
  "lpn/lvn - medication exam": "lpn / lvn - medication exam",
  "public health laboratory assistant": "laboratory assistant",
  "nurse practitioner (adult)": "nurse practitioner - adult",
  "general ultrasound": "ultrasound technologist",
  "rn - intensive care unit medication": "rn - intensive care unit (icu) medication",
  "pca_pct - general": "pca / pct - general",
  "lpn/lvn - crisis care": "lpn / lvn - crisis care",
  "rn - long term care - skilled nursing facility nurse": "rn - long term care - skilled nursing facility",
  "rn - operating room (or) medication": "rn - operating room (or) medications",
  "respiratory therapist - pharmacology": "respiratory therapist - medication",
  "cna - long term care": "cna - long-term care",
  "registered nurse first assistant (rnfa)": "rn - first assistant (rnfa)",
  "cardiovascular operating room (cvor) technician": "cardiovascular operating room (cvor) technologist",
  "rn - long term care pharmacology": "rn - long-term care medication",
  "speech language therapist": "speech language pathologist",
  "lpn/lvn - home health": "lpn / lvn - home health",
  "lpn_lvn - medical-surgical": "lpn / lvn - medical-surgical",
  "certified surgical technologist first assist": "certified surgical technologist first assistant",
  "polysomnography technician": "polysomnographer",
  "lpn_lvn - skilled nursing facility": "lpn / lvn - skilled nursing facility",
  "lpn_lvn - psychiatric": "lpn / lvn - psychiatric",
  "rn - operating room (or)/ perioperative – pediatrics": "rn - operating room (or) / perioperative – pediatrics",
  "rn - emergency room - pediatric": "rn - emergency room - pediatrics",
  "lpn/lvn - clinic/ambulatory": "lpn / lvn - clinic / ambulatory",
  "lpn/lvn - psychiatric": "lpn / lvn - psychiatric",
  "licensed master social worker (lmsw)": "licensed master social worker",
  "lpn/lvn - iv therapy": "lpn / lvn - iv therapy",
  "pca/pct - medical - surgical": "pca / pct - medical surgical",
  "pca/pct - general": "pca / pct - general",
  "lpn_lvn - hospice care": "lpn / lvn - hospice care",
  "lpn/lvn - medical surgical": "lpn / lvn - medical-surgical",
};

export const realExamShells = [
  "1-Hour Post Hospitalization Education for Myocardial Infarction Patients",
  "12HR Bundle - Prevention Medical Errors (1HR)",
  "Hourly Rounding and Patient Handoff",
  "Implicit Bias Training",
  "Medication Administration",
  "HIPAA-Obstetric-Gynecology (Narration)",
];

export const scTitlesMapping = {
  "pt - home health": "physical therapist - home health",
  "physical therapist": "physical therapist (pt)",
  "medical surgical - telemetry nurse": "rn - medical-surgical - telemetry",
  "rn - home health": "rn - home health",
  "rn - medical surgical - telemetry": "rn - medical-surgical - telemetry",
  "rn - hospice": "rn - hospice",
  "licensed practical nurse (lpn) - school": "lpn / lvn - school",
  "licensed practical nurse (lpn) - home health": "lpn / lvn - home health",
  "licensed practical nurse (lpn) - long term care": "lpn / lvn - long term care",
  "occupational therapist": "occupational therapist",
  "physical therapist (pt)": "physical therapist (pt)",
  "medical surgical nurse": "rn - medical-surgical",
  "medical - surgical nurse": "rn - medical-surgical",
  "long term care nurse": "rn - long-term care",
  "lpn/lvn - home health": "lpn / lvn - home health",
  "occupational therapist (ot)": "occupational therapist",
  "speech language therapist": "speech language pathologist",
  "physical therapy assistant (pta)": "physical therapy assistant",
  "lpn/lvn -rehab": "lpn / lvn - rehab",
  "telemetry nurse": "rn - telemetry",
  "medical technologist - clinical laboratory scientist": "medical technologist / clinical laboratory scientist",
  "surgical technologist": "surgical technologist",
  "oncology nurse": "rn - oncology",
  "rn - interventional radiology": "rn - interventional radiology",
  "long term care - skilled nursing facility nurse": "rn - long term care - skilled nursing facility",
  "rn - cardiovascular progressive care unit (pcu)(copy)":
    "rn - stepdown / intermediate care / progressive care unit (pcu)",
  "pharmacist skills checklist": "pharmacist",
  "post anesthesia care unit (pacu) nurse": "rn - post anesthesia care unit (pacu)",
  "lpn/lvn - clinic/ambulatory": "lpn / lvn - clinic / ambulatory",
  "nurse supervisor": "rn - supervisor",
  "rn - labor and delivery": "rn - labor and delivery",
  "rn - hospital-based case manager": "rn - hospital-based case manager",
  "perioperative nurse": "rn - operating room (or) / perioperative - adult",
  "rn - stepdown - intermediate care - progressive care unit (pcu)":
    "rn - stepdown / intermediate care / progressive care unit (pcu)",
  "licensed practical nurse (lpn) - hospice care": "lpn / lvn - hospice care",
  "rn - oncology": "rn - oncology",
  "physical therapy assistant": "physical therapy assistant",
  "wound care nurse": "rn - wound care",
  "stepdown nurse": "rn - stepdown / intermediate care / progressive care unit (pcu)",
  "rn - supervisor": "rn - supervisor",
  "pediatric intensive care unit (picu) nurse": "rn - intensive care unit (icu) - pediatrics",
  "rn - first assistant (rnfa)": "rn - first assistant (rnfa)",
  "surgical first assistant": "surgical first assistant",
  "registered nurse first assistant (rnfa)": "rn - first assistant (rnfa)",
  "rn - gastrointestinal (gi)": "rn - gastrointestinal (gi)",
  "occupational therapy assistant": "occupational therapist assistant",
  "rn - orthopedic": "rn - orthopedic",
  "rn - telemetry": "rn - telemetry",
  "rn - operating room  (or) / preoperative": "rn - operating room (or) / perioperative - adult",
  "licensed practical nurse (lpn)": "lpn / lvn - adult / general",
  "progressive care unit - nurse": "rn - stepdown / intermediate care / progressive care unit (pcu)",
  "certified surgical technologist first assist": "certified surgical technologist first assistant",
  "neonatal intensive care unit (nicu) nurse": "rn - neonatal intensive care unit (nicu)",
  "psychiatric nurse": "rn - psychiatric - adult",
  "postpartum nurse skills checklist": "rn - postpartum",
  "rn - cardiac catheterization laboratory": "rn - cardiac catheterization laboratory",
  "pediatric nurse": "rn - pediatrics",
  "nursery and mother baby": "rn - mother-baby and nursery",
  "nurse educator": "rn - health educator",
  "rn - case manager": "rn - case manager",
  "interventional radiology technologist": "interventional radiology technologist",
  "rn - postpartum": "rn - postpartum",
  "rn - peripherally inserted central catheters (picc)": "rn - peripherally inserted central catheter (picc)",
  "rn - critical care": "rn - intensive care unit (icu)",
  "clinical nurse manager": "rn - clinical manager",
  "rn - medical surgical": "rn - medical-surgical",
  "utilization review specialist": "utilization review specialist",
  "rn - emergency room (er)": "rn - emergency room - adult/general",
  "licensed vocational nurse (lvn)": "lpn / lvn - adult / general",
  "medical-surgical nurse": "rn - medical-surgical",
  "school nurse": "rn - school",
  "respiratory therapist": "respiratory therapist – general",
  "medical assistant(2)": "medical assistant",
  "correctional nurse": "rn - correctional",
  "rn - psychiatric - pediatric": "rn - psychiatric - pediatrics",
  "lpn/lvn - adult/general": "rn - psychiatric - pediatrics",
  "nurse practitioner": "nurse practitioner - adult",
  "rn - pediatric": "rn - pediatrics",
  "rn - intensive care unit (icu) - pediatric": "rn - intensive care unit (icu) - pediatrics",
  "cardiovascular nurse": "rn - cardiovascular",
  "electrocardiogram (ekg) technician": "electrocardiogram (ekg/ecg) technician",
  "lpn/lvn - school": "lpn / lvn - school",
  "echocardiography (ecg) technologist(copy)(copy)": "echocardiography technologist",
  "rn - intermediate care unit - pediatric":
    "rn - stepdown / intermediate care unit / transitional care unit (tcu) - pediatrics",
  "rn -operating room - scrub": "rn - operating room (or) - scrub",
  "mental health aide adult": "mental health aide (mha) - adult",
  "mental health aide pediatrics": "mental health aide (mha) - pediatrics",
  "clinical microbiologist/clinical lab specialist": "clinical microbiologist - clinical laboratory specialist",
  "licensed vocational nurse (lvn) - long term care": "lpn / lvn - long term care",
  "public health nurse": "rn - public health",
  "social worker": "unlicensed social worker",
  "medical records technician": "medical records clerk",
  "medical laboratory technician (mlt) - adult": "medical laboratory technician (mlt)",
  "public health laboratory assistant": "laboratory assistant",
  "intravenous therapy nurse": "rn - intravenous therapy",
  "care giver(deleted-2)": "caregiver",
  "postpartum nurse": "rn - postpartum",
  "pca/pct - general": "pca / pct - general",
  "lpn/lvn - long term care": "lpn / lvn - long term care",
  "cna - long term care": "cna - long-term care",
  "lpn/lvn - acute care": "lpn / lvn - acute care",
  "orthopedic nurse": "rn - orthopedic",
  "lpn/lvn - psychiatric": "lpn / lvn - psychiatric",
  "licensed clinical social worker (lcsw)": "licensed clinical social worker",
  "triage nurse": "rn - triage",
  "sterile processing technician (spt)": "sterile processing technician",
  "hospice nurse": "rn - hospice",
  "licensed practical nurse (lpn) - psychiatric": "lpn / lvn - psychiatric",
  "pediatric operating room nurse": "rn - operating room (or) / perioperative – pediatrics",
  "patient care technician": "pca / pct - general",
  "pre-operative nurse": "rn - operating room (or) - pre-operative",
  "rn - emergency room - pediatric": "rn - emergency room - pediatrics",
  "nursery and mother baby nurse": "rn - mother-baby and nursery",
  "rn - long term care": "rn - long-term care",
  "registered nurse": "rn - medical-surgical",
  "licensed practical nurse (lpn) - medical-surgical": "lpn / lvn - medical-surgical",
  "rn - operating room (or)/perioperative - adult": "rn - operating room (or) / perioperative - adult",
  "rn - operating room (or)/perioperative": "rn - operating room (or) / perioperative - adult",
  "cna - medical/surgical": "cna - medical surgical",
  "emergency medical technician (emt)": "emergent medical technician (emt)",
};

export const realModuleShells = ["HIPAA Basics", "Workplace Violence (Narration)"];

export const moduleTitlesMapping = {
  "1-hour sexual harassment prevention training": "sexual harassment prevention training - general",
};

export const documentsToNotImport = [
  "Ambulatory Health Care: 2023 National Patient Safety Goals",
  "Assisted Living Community: 2023 National Patient Safety Goals",
  "Behavioral Health Care and Human Services: 2023 National Patient Safety Goals",
  "Critical Access Hospital: 2023 National Patient Safety Goals",
  "Hospital: 2023 National Patient Safety Goals",
  "Laboratory Services: 2023 National Patient Safety Goals",
  "Nursing Care Center: 2023 National Patient Safety Goals",
  "Office-Based Surgery: 2023 National Patient Safety Goals",
  "Home Care: 2023 National Patient Safety Goal",
  "HIPAA Training Module",
  "OSHA Training",
  "Hand Hygiene",
  "Domestic - Intimate Partner Abuse Training",
  "Child Abuse",
  "Elderly Abuse",
  "Advance Directive",
  "Age Specific Training",
];
